version: "3.8"
services:
  redis:
    image: "redis:7.2.4"
    container_name: redis
    ports:
      - "6379:6379"

  fastapi:
    build: .
    container_name: fastapi
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    container_name: worker
    volumes:
      - .:/app
    command: rq worker --url redis://redis:6379/0
    depends_on:
      - redis
